In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import numpy as np
from vae.arch_vaegan import VAE
import matplotlib.pyplot as plt
import os
from IPython import display
from ipywidgets import interact, interactive, fixed, interact_manual, FloatSlider
import ipywidgets as widgets
from tensorflow.keras.utils import plot_model
from tensorflow.keras import backend as K

K.set_image_data_format('channels_last')
np.set_printoptions(precision=4, suppress = True)

In [4]:
vae = VAE()
vae.set_model('./vae')

In [5]:
DIR_NAME = './data/rollout/'
file = os.listdir(DIR_NAME)[200]
print(file)
obs_data = np.load(DIR_NAME + file)['obs']
print(obs_data.shape)

490127640.npz
(300, 64, 64, 3)


In [6]:
plot_model(vae.E, to_file='./vae/encoder.png', show_shapes=True)
plot_model(vae.G, to_file='./vae/decoder.png', show_shapes=True)
plot_model(vae.D, to_file='./vae/discriminator.png', show_shapes=True)

('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')
('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')
('Failed to import pydot. You must `pip install pydot` and install graphviz (https://graphviz.gitlab.io/download/), ', 'for `pydotprint` to work.')


In [10]:
### output from one episode

for idx in range(0,300):
    plt.gca().cla() 
    
    obs = obs_data[idx]
    print(obs.shape)
    z_decoded = vae.predict(np.array([obs]))[0]
    break

    plt.subplot(121)
    plt.imshow( obs)
    plt.subplot(122)
    plt.imshow( z_decoded)
    
#     plt.show()
    display.clear_output(wait=True)
    display.display(plt.gcf()) 

[[[0.4 0.8 0.4]
  [0.4 0.8 0.4]
  [0.4 0.8 0.4]
  ...
  [0.4 0.8 0.4]
  [0.4 0.8 0.4]
  [0.4 0.8 0.4]]

 [[0.4 0.8 0.4]
  [0.4 0.8 0.4]
  [0.4 0.8 0.4]
  ...
  [0.4 0.8 0.4]
  [0.4 0.8 0.4]
  [0.4 0.8 0.4]]

 [[0.4 0.8 0.4]
  [0.4 0.8 0.4]
  [0.4 0.8 0.4]
  ...
  [0.4 0.8 0.4]
  [0.4 0.8 0.4]
  [0.4 0.8 0.4]]

 ...

 [[0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]
  ...
  [0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]]

 [[0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]
  ...
  [0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]]

 [[0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]
  ...
  [0.  0.  0. ]
  [0.  0.  0. ]
  [0.  0.  0. ]]]


ValueError: Layer model_1 expects 1 input(s), but it received 3 input tensors. Inputs received: [<tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[-0.0406,  0.0161,  0.1911,  0.026 , -0.0529, -0.0101, -0.0978,
         0.0359,  0.1099,  0.1136, -0.1232,  0.0472, -0.0414,  0.0093,
         0.1313, -0.0587, -0.0926,  0.0176, -0.0435,  0.1233, -0.0891,
        -0.0317,  0.078 , -0.1996,  0.1191,  0.1518,  0.0317,  0.1662,
        -0.0226,  0.0609, -0.003 , -0.1615]], dtype=float32)>, <tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[-0.02  ,  0.0663,  0.0118,  0.0673, -0.0007, -0.0008,  0.0644,
        -0.0162,  0.0334, -0.0905,  0.0795,  0.161 , -0.0302, -0.113 ,
         0.0337, -0.106 , -0.0263,  0.0229,  0.0451, -0.1276, -0.0496,
         0.0342,  0.0051, -0.1451,  0.2147,  0.005 , -0.1455, -0.0873,
         0.0263,  0.0528, -0.0953, -0.0545]], dtype=float32)>, <tf.Tensor: shape=(1, 32), dtype=float32, numpy=
array([[ 1.3727,  1.4593, -1.0083,  0.3695,  0.5637, -1.5488, -0.0366,
         0.8075,  0.8217, -0.9374, -0.137 ,  2.2239,  1.1854,  0.2514,
         3.1022,  0.621 , -0.5722,  0.7774, -0.6999, -0.4573, -1.8754,
        -1.5355, -0.5296, -0.6925, -1.5013,  0.6905, -0.1447, -1.021 ,
         1.069 ,  0.8363,  0.3983, -0.9526]], dtype=float32)>]

In [ ]:
### output from the full_model
DIR_NAME = './data/rollout/'
file = os.listdir(DIR_NAME)[179]
obs_data = np.load(DIR_NAME + file)['obs']

obs = obs_data[50]
reconstruction = vae.predict(np.array([obs]))[0]

ax1 = plt.subplot(121)
plt.imshow( obs)
ax1.axis('off')
ax1.text(0.5,-0.1, "INPUT", size=12, ha="center", 
         transform=ax1.transAxes)

ax2 = plt.subplot(122)
plt.imshow( reconstruction)
ax2.axis('off')
ax2.text(0.5,-0.1, "OUTPUT", size=12, ha="center", 
         transform=ax2.transAxes);


In [ ]:
mus, log_vars, _  = vae.E.predict(np.array([obs]))
mu = mus[0]
log_var = log_vars[0]
print("mu = " + str(mu))
print("log_var = " + str(log_var))

encoded_z = vae.E.predict(np.array([obs]))[0]
print("z = " + str(encoded_z))

In [ ]:
plt.plot(mu);
plt.plot(log_var);
print('informative dimensions:')
hot_zs = np.where(abs(log_var) > 0.5)[0]
hot_zs

In [ ]:
file1 = os.listdir(DIR_NAME)[100]
obs_data1 = np.load(DIR_NAME + file)['obs']
file2 = os.listdir(DIR_NAME)[140]
obs_data2 = np.load(DIR_NAME + file)['obs']

In [ ]:
vae.E.predict(np.array([obs_data1[20]]))

In [ ]:
top_left = vae.E.predict(np.array([obs_data1[20]]))[2][0]
top_right = vae.E.predict(np.array([obs_data1[60]]))[2][0]
bottom_left = vae.E.predict(np.array([obs_data2[80]]))[2][0]
sample_z = vae.E.predict(np.array([obs_data[60]]))[2][0]

fig, axes = plt.subplots(nrows=5, ncols=5, figsize=(32,32), sharex=True, sharey=True)
plt.subplots_adjust(hspace = 0.4)

for x in range(5):
    for y in range(5):
        
        z = sample_z.copy()

#         z = top_left + (top_right - top_left) * x/8 + (bottom_left - top_left) * y/8
        z[7] = (x-2)
        z[10] = (y-2)
        
        decoded_obs = vae.G.predict(np.array([z]))[0]
        
        axes[x,y].set_axis_off()
        
        axes[x,y].imshow(decoded_obs)
        
        axes[x,y].text(0.5,-0.1, 'z[7] ' + str(np.round(z[7],2)), size=20, ha="center", 
                       transform=axes[x,y].transAxes)
        
        axes[x,y].text(0.5,-0.2, 'z[10] = ' + str(np.round(z[10],2)), size=20, ha="center", 
                       transform=axes[x,y].transAxes)
    

plt.show()

In [ ]:
def play_with_z(z0 = sample_z[0]
                ,z2 = sample_z[2]
                ,z4 = sample_z[4]
                ,z5 = sample_z[5]
                ,z6 = sample_z[6]
                ,z7 = sample_z[7]
                ,z10 = sample_z[10]
                ,z15 = sample_z[15]
                ,z24= sample_z[24]
                ,z25= sample_z[25]
                ,z27= sample_z[27]
                ):
    z = sample_z.copy()
    z[0] = z0
    z[2] = z2
    z[4] = z4
    z[5] = z5
    z[6] = z6
    z[7] = z7
    z[10] = z10
    z[15] = z15
    z[24] = z24
    z[25] = z25
    z[27] = z27
    
    decoded_obs = vae.G.predict(np.array([z]))[0]
    plt.gca().cla() 
    plt.imshow( decoded_obs)

In [ ]:
interact(play_with_z
        , z0=(-3.0,3.0,0.1)
        , z2=(-3.0,3.0,0.1)
        , z4=(-3.0,3.0,0.1)
        , z5=(-3.0,3.0,0.1)
        , z6=(-3.0,3.0,0.1)
        , z7=(-3.0,3.0,0.1)
        , z10=(-3.0,3.0,0.1)
        , z15=(-3.0,3.0,0.1)
        , z24=(-3.0,3.0,0.1)
        , z25=(-3.0,3.0,0.1)
        , z27=(-3.0,3.0,0.1)
        )